### ISSUE TITLE
Turborepo support (Currently `INIT_CWD` workaround required)

### ISSUE THREAD

**Issue by 0xdhrv** [contentlayerdev/contentlayer#104]
When using contentlayer inside turbo repo, the config gives an error for importing `contentlayer/source-files`

This is the same repository for reproduction of the same: [https://github.com/0xdhrv/turborepo-with-contentlayer](https://github.com/0xdhrv/turborepo-with-contentlayer)

And, inside `apps/starter`

**Comment by schickling** [comment]
Hi @0xdhrv. Thanks for opening this issue and providing a repro. I've just given it a try and can confirm the problem you're running into. This is currently happening due to a limitation in Turborepo itself (see https://github.com/vercel/turborepo/issues/485).

However, until this is resolved you can workaround the problem by simply adding `INIT_CWD=$PWD` in front of `next build` in your `package.json` like the following:


```js
// apps/starter/package.json
  "scripts": {
     // ...
    "build": "INIT_CWD=$PWD next build",
    // ...
  },
```

**Comment by pomber** [comment]
I'm having the [same issue with lerna](https://github.com/code-hike/codehike/pull/170#issuecomment-1114210419). The `INIT_CWD=$PWD` trick works, but I'd prefer to avoid it.

**Comment by jrolfs** [comment]
Yeah, same here but with Yarn workspaces... discovered the `INIT_CWD` thing myself before finding this issue. What's the intention behind reading from `INIT_CWD` when resolving the working directory?

https://github.com/contentlayerdev/contentlayer/blob/20ce9059ca7da34a2a7eb9b7650be2b6bcde6cdd/packages/@contentlayer/core/src/cwd.ts#L9-L13

**Comment by jrolfs** [comment]
@schickling I think ultimately it makes sense to be available in both places, right? That said, I think I would prefer a CLI argument as I have a build step on CI that invokes `contentlayer build` directly.

I could probably take a stab at this, although admittedly there's a bit of a learning curve with this codebase on account of **Effect-TS** (and its lack of documentation 😜).

-----------

Here's a bunch of detail around my specific case, just so you have it when considering all the idiosyncrasies of package managers 😅 

I am using Yarn 1's `workspace` command and it seems the issue is that it _does_ set `INIT_CWD` to the root of the repository in this specific case (even though `process.cwd()` resolves to the package (workspace) in which the package script is being invoked.

#### Example

Configuration lives @ `~/my-monorepo/packages/site/contentlayer.config.ts`

`~/my-monorepo/package.json`
```json
{
  "name": "my-monorepo",
  "scripts": {
    "start:site": "yarn workspace @foo/site run start",
    "build:site": "yarn workspace @foo/site run build"
  }
}
```

`~/my-monorepo/packages/site/package.json`
```json
{
  "name": "@foo/site",
  "scripts": {
    "start": "next dev",
    "build:site": "contentlayer build"
  }
}
```

From `~/my-monorepo`
```sh
yarn start:site
```
and
```sh
yarn build:site
```
...both fail to find the configuration because `INIT_CWD` is set to `~/my-monorepo` (not `~/my-monorepo/packages/site, which is what `process.cwd()` returns).

_However_ — if I invoke `yarn workspace @foo/site run build` directly from `~/my-monorepo`, `INIT_CWD` _is not set_, and therefore the configuration is resolved correctly.

I'm hoping to get onto Yarn 2+ soon in this project, and I'm curious if it has different behavior for `INIT_CWD` in these cases. I'm not sure what the "standard" behavior is supposed to be for `INIT_CWD`, though. Yarn 1 does seem to always set `process.cwd()` correctly when scripts are invoked on sub-packages.

------------

Finally, I just want to say nice work so far on **contentlayer**. I really like the approach y'all are taking and I'm so glad I found it :)

**Comment by jrolfs** [comment]
Huh, I guess I missed that CLI flag as I was originally looking for the Next.js case... unfortunately it seems to have issues as well (and from playing around it seems like the path provided is _relative_ to `INIT_CWD` which kinda brings along the same set of problems?)

<img width="1289" alt="--configuration" src="https://user-images.githubusercontent.com/288160/168399521-c4ca427a-8d1e-4fc4-bafb-32f812df9768.png">

Maybe I'm missing something or oversimplifying things but I'm pretty sure most tools just use `process.cwd()` and "just work" (lots of assumptions there as obviously I haven't looked at how everything works).

**Comment by schickling** [comment]
@jrolfs would you please mind opening a new issue for this with a reproduction repo? (Ideally also including some snippets how you would like it to work vs how it's currently working.)

(PS: In the upcoming version you'll be able to specify the config path in the Next.js plugin - see #248)

**Comment by schickling** [comment]
This should be addressed with the [`0.2.8` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.2.8). 🎉

**Comment by Aaditya-23** [comment]
I am getting this error at build step. I am using next13 and monorepo

**Comment by rtorcato** [comment]
This still is a problem in turbo repo. INIT_CWD doesn't work for me either.

**Comment by rtorcato** [comment]
I removed this line from my next.config and my turbo repo setup now works for me.

const { withContentlayer } = require('next-contentlayer')

I am using tsup to build my package, but the error was still appearing in my turbo build. 

is there any reason I would need withContentLayer in a mono repo? when I build my markdown package I am getting refreshed content on my nextjs app and everything looks ok.
