### ISSUE TITLE
I got error while parse post.body.code with useMDXComponent

### ISSUE THREAD

**Issue by stevenKirill** [contentlayerdev/contentlayer#126]
TypeError: Cannot read properties of undefined (reading 'default') 
![image](https://user-images.githubusercontent.com/47239173/153757369-44f6feb5-591a-48ca-860a-d683ce34f400.png)

**Comment by schickling** [comment]
Thanks for opening this issue @stevenKirill. Are you sure you followed the upgrade instructions of the [0.1.0 release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.1.0) and changed `bodyType` to `contentType`?

**Comment by stevenKirill** [comment]
Hey tnaks i fixed this erorr!

**Comment by stevenKirill** [comment]
But i have another question. Coulf you help me how can I make that my .contentlayer folder appear in node_modules folder while i deploy my app? So I don't need to commit it so I can use imports like this
![content1](https://user-images.githubusercontent.com/47239173/154804806-05e12272-40d0-4131-929f-b27fbca3d35f.png)
![content2](https://user-images.githubusercontent.com/47239173/154804815-068d0440-88d5-44b6-82b5-1de08e4977d5.png)
![content3](https://user-images.githubusercontent.com/47239173/154804821-cf208891-8972-41ab-a5d0-f6f12e81bb7d.png)

**Comment by stevenKirill** [comment]
I'm getting error while build my app like this
![builderr](https://user-images.githubusercontent.com/47239173/154804898-b29b68b6-1e64-4194-a455-0ef75ab3c6ba.png)

**Comment by schickling** [comment]
Are you sure you followed [these upgrade instructions](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.1.0) properly? 

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1567498/155989090-4766355d-a99e-4f6a-b114-a40931c31d8a.png">

If you're still running into problems please share a reproduction repository link here. Thanks!

**Comment by guangxue** [comment]
> 

I did follow this step but still get the same error when run `npm run build`, however, no issue when run `npm run dev`.

<img width="1199" alt="Screenshot 2023-02-14 at 11 03 27 am" src="https://user-images.githubusercontent.com/17754308/218602263-bd2f234f-5a57-4984-af59-18dc263dbf35.png">

<img width="1168" alt="Screenshot 2023-02-14 at 11 03 00 am" src="https://user-images.githubusercontent.com/17754308/218602325-53eba60a-d0b1-476a-8150-ba84a017a15e.png">

<img width="896" alt="Screenshot 2023-02-14 at 11 05 09 am" src="https://user-images.githubusercontent.com/17754308/218602496-5851aa9d-c6d1-473a-afb7-9aee6cd6c334.png">

**Comment by giri14mct** [comment]
I deleted the *node_modules* folder and reinstalled it, and that worked for me
