### ISSUE TITLE
No `.contentlayer` folder is generated in Next.js 13.3

### ISSUE THREAD

**Issue by qiushiyan** [contentlayerdev/contentlayer#415]
Seems contentlayer is currently imcompatible with the latest version of Next.js 13.3, when I run `next dev` non `.contentlayer` folder is generated. 

I cloned the [example project](https://www.contentlayer.dev/examples/nextjs) locally, deleted `.contentlayer` and run 

```
pnpm add next@latest react@latest react-dom@latest
```

After this `pnpm run dev` does not generated the `.contentlayer` folder.

**Comment by cibulka** [comment]
Yes, having the same problem. Downgrading to 13.2.4 works, assuming you overwrote telemetry dependency [as described here](https://github.com/contentlayerdev/contentlayer/issues/386).

**Comment by kamto7** [comment]
Same problem, but downgrading to 13.2.4 will encounter other next problems, can anyone provide some help?

**Comment by kamto7** [comment]
I have found the cause of this problem.
Since `next@v13.2.5-canary.27`, next dev has been using jest-worker to start the service.

Using a version below `next@v13.2.5-canary.26` will not have this problem.
Of course, the best solution is to optimize the way of next config plugin.

**Comment by nkilm** [comment]
**what triggers the creation of `.contentlayer` folder?** I have degraded my nextjs version to `13.2.4` from `13.3.0` but the folder is still not getting generated. 
```js
// next.config.js

/** @type {import('next').NextConfig} */
const { withContentlayer } = require("next-contentlayer");

const nextConfig = {
  reactStrictMode: true,
  distDir: "build",
  experimental: {
    appDir: true,
  },
};

module.exports = withContentlayer(nextConfig);
```

**Comment by harshhhdev** [comment]
Just saw this issue. My contentlayer is working fine (check: [harshhhdev/www](https://github.com/harshhhdev/www)), but it's because I'm using `0.3.0` instead of `0.3.1`.

**Comment by kamto7** [comment]
> Is this a bug with Next 13.3 or is it a bug with contentlayer?

It's just a matter of how the plugin is started

**Comment by thara003** [comment]
I too have the same issue, here's my package.json

```
    "next": "13.3.0",
    "next-contentlayer": "^0.3.0",
    "contentlayer": "^0.3.0",
```

also tried downgrading the versions just like the [contentlayer-example](https://github.com/contentlayerdev/next-contentlayer-example/blob/main/package.json) still the issue persist.

**Comment by yeganathan18** [comment]
@qiwang97 these are same versions used in [contentlayer-example](https://github.com/contentlayerdev/next-contentlayer-example/blob/main/package.json), but still it doesn't work.

```json
    "contentlayer": "^0.3.0",
    "next": "13.2.5-canary.16",
    "next-contentlayer": "^0.3.0",
```

I used the above example from[ leerob's portfolio repository](https://github.com/leerob/leerob.io/blob/main/package.json) and it works fine.

**Comment by TheBinaryGuy** [comment]
Until this is resolved, you can either use [concurrently](https://github.com/open-cli-tools/concurrently) to work around this:
```json
{
  // ---
  "scripts": {
    "dev": "concurrently \"contentlayer dev\" \"next dev\"",
    "build": "contentlayer build && next build"
  }
  / ---
}
```

Or have 2 different scripts for development and run them both in different tabs:
```json
{
  // ---
  "scripts": {
    "cl-dev": "contentlayer dev",
    "dev": "next dev",
    "build": "contentlayer build && next build"
  }
  / ---
}
```

**Comment by gsen** [comment]
Local fix until this issue is resolved.
You can update the dev script in package.json and make use of the content layer cli as follows: 
```json
"scripts": {
    "dev": "contentlayer dev & next dev"
}
```
then run 
`pnpm dev`

Content layer cli - https://www.contentlayer.dev/docs/reference/cli#dev

**Comment by hendrickson02** [comment]
> > @qiwang97 these are same versions used in [contentlayer-example](https://github.com/contentlayerdev/next-contentlayer-example/blob/main/package.json?rgh-link-date=2023-04-11T15%3A28%3A58Z), but still it doesn't work.
> > ```json
> >     "contentlayer": "^0.3.0",
> >     "next": "13.2.5-canary.16",
> >     "next-contentlayer": "^0.3.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I used the above example from[ leerob's portfolio repository](https://github.com/leerob/leerob.io/blob/main/package.json?rgh-link-date=2023-04-11T15%3A28%3A58Z) and it works fine.
> 
> Thank you! This versions are working for me🎉
> 
> Alterly, you can try `npx contentlayer dev`, it also generates the `.contentlayer` folder.

In order to generate the `.contentlayer/generated` folder, you will need to run `npx contentlayer postinstall` as well. I don't know why that isn't being run when I run `npx contentlayer dev` or `npx contentlayer build` though. :shrug:

**Comment by Perjan** [comment]
> Local fix until this issue is resolved. You can update the dev script in package.json and make use of the content layer cli as follows:
> 
> ```json
> "scripts": {
>     "dev": "contentlayer dev & next dev"
> }
> ```
> 
> then run `pnpm dev`
> 
> Content layer cli - https://www.contentlayer.dev/docs/reference/cli#dev

This worked for me as well.

**Comment by weleo** [comment]
> Local fix until this issue is resolved. You can update the dev script in package.json and make use of the content layer cli as follows:
> 
> ```json
> "scripts": {
>     "dev": "contentlayer dev & next dev"
> }
> ```
> 
> then run `pnpm dev`
> 
> Content layer cli - [contentlayer.dev/docs/reference/cli#dev](https://www.contentlayer.dev/docs/reference/cli#dev)

Little side note: Due to how `&`works, `contentlayer dev & next dev`runs concurrently on macOS and Linux, but for example, runs sequentially in PowerShell. So if you need consistency for this edge case, you may want to go with `concurrently \"contentlayer dev\" \"next dev\"`.

**Comment by schickling** [comment]
This should be addressed with the [`0.3.2` release](https://github.com/contentlayerdev/contentlayer/releases/tag/v0.3.2). 🎉

**Comment by weijunext** [comment]
> work fine with these configs( see [my forked example](https://github.com/qiwang97/next-contentlayer-v0.3.1-example) ):
> 
> ```
>  "next": "13.2.4",
>  "next-contentlayer": "0.3.1",
> "contentlayer": "0.3.1"
> ```

It works. Thank you!

**Comment by saifookhan** [comment]
Also works with 🚀 
```
"contentlayer": "0.3.3",
"next": "13.3.0",
"next-contentlayer": "0.3.3"
```

**Comment by konsalex** [comment]
Still having the same issue with versions `0.3.1` and `0.3.3` and the behaviour is quite flaky, as it worked and then suddenly stopped working so not sure exactly the reason behind it.

**Comment by konsalex** [comment]
@weijunext remark is not even installed. Should it be?

**Comment by konsalex** [comment]
After investigation, I suspect that it has to do something with orphan processes staying in the background? Not entirely sure, but after closing iTerm, both iTerm, WebStorm and VSCode servers started working as expected 🤔

Reference also to here: https://github.com/shadcn-ui/taxonomy/issues/122

**Comment by tanishbaansal** [comment]
Simply going to `cd apps/www/` and doing `npm run build` generated the content layer generated folder for me 

<img width="534" alt="image" src="https://github.com/contentlayerdev/contentlayer/assets/7449806/c6bd7182-d080-4371-98c0-d1e0d14a844e">

**Comment by aloptrbl** [comment]
my only solution is put the .md files in data folder
`data/posts/post-1.md`
![Screenshot 2024-03-08 at 7 02 58 AM](https://github.com/contentlayerdev/contentlayer/assets/13547100/d68d108c-7aa3-4e15-b3f7-a8070f0571ac)

work on latest version of next.js
`"dependencies": {
"contentlayer": "^0.3.4",
"next": "latest",
"next-contentlayer": "^0.3.4",
}
`

**Comment by angryred027** [comment]
> Seems contentlayer is currently imcompatible with the latest version of Next.js 13.3, when I run `next dev` non `.contentlayer` folder is generated.
> 
> I cloned the package.json, next.config.js and contentlayer config file from the [example project](https://www.contentlayer.dev/examples/nextjs) and run the following comand to update nextjs
> 
> ```
> pnpm add next@latest react@latest react-dom@latest
> ```
> 
> After this `pnpm run dev` does not generated the `.contentlayer` folder.
> 
> [example repo](https://github.com/qiushiyan/next13.3-contentlayer)

I just faced into the same issue.

I cloned the example repo from github, but it does not work properly.

    "contentlayer": "^0.3.4",
    "framer-motion": "^10.18.0",
    "next": "15.3.0",
    "next-contentlayer": "^0.3.4",
    "ogl": "^1.0.11",
    "pol-ui": "^2.1.1052",
    "react": "19.1.0",

This is a piece of the package.json file content.

How to fix it?
